# Generated by Django 2.2.1 on 2019-09-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Username',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('sex', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('education', models.CharField(max_length=20)),
                ('research', models.CharField(max_length=100)),
            ],
        ),
    ]
