# Generated by Django 2.2.1 on 2019-08-26 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rectangle',
        ),
    ]
