# Generated by Django 2.2.1 on 2019-09-02 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('did', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('consumingtime', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rectangle',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('x1', models.FloatField()),
                ('y1', models.FloatField()),
                ('x2', models.FloatField()),
                ('y2', models.FloatField()),
                ('duration', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='backend.Duration')),
            ],
        ),
    ]
