# Generated by Django 2.2.1 on 2019-09-03 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_duration_rectangle'),
    ]

    operations = [
        migrations.AddField(
            model_name='duration',
            name='username',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='backend.Username'),
        ),
        migrations.AddField(
            model_name='rectangle',
            name='username',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='backend.Username'),
        ),
    ]
