# Generated by Django 2.2.1 on 2019-08-28 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rectangle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rectangle',
        ),
    ]
