# Generated by Django 2.2.1 on 2019-08-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_rectangle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('consumingtime', models.IntegerField()),
            ],
        ),
    ]
