# Generated by Django 2.2.1 on 2019-08-28 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_duration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Duration',
        ),
        migrations.DeleteModel(
            name='Rectangle',
        ),
    ]
