# Generated by Django 2.2.1 on 2019-08-28 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_duration_rectangle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Duration',
        ),
        migrations.DeleteModel(
            name='Rectangle',
        ),
    ]
